### ISSUE TITLE
Reintroduce rate limiting

### ISSUE THREAD

**Issue by Ar4l** [AISE-TUDelft/coco#11]
Found two FastAPI rate limiters, each with an implementation issue:

1. [`slowapi`](https://slowapi.readthedocs.io/en/latest/): does not support websocket streaming.
2. [`fastapi-limiter`](https://pypi.org/project/fastapi-limiter/): requires running redis docker container to maintain rate/user in-memory (this is probably overkill for our mvp). 

We need to either search for alternatives or address the issue in one of these libraries. Writing our own for an MVP is also not out of the question, we simply maintain a set in-memory.

**Comment by RebelOfDeath** [comment]
As far as I can tell, the basis for this has been set (although testing of this might prove otherwise); it is for this reason that I will close this issue. In #10 with the more rigorous testing that will be conducted potentially stimulating changes to the implementation outlined here.
