### ISSUE TITLE
Introduction of pre-commit

### ISSUE THREAD

**Issue by RebelOfDeath** [AISE-TUDelft/coco#14]
# Proposal: Introduce Pre-commit Hooks to the Project

## Overview

As our project grows in complexity, maintaining code quality and consistency becomes increasingly challenging. To address this, I propose introducing pre-commit hooks as part of our development workflow. Pre-commit hooks can help us catch issues early, enforce coding standards, and ensure that only well-formatted and properly tested code makes it into our repository.

## Benefits

1. **Automated Code Quality Checks**: Pre-commit hooks can automate code formatting, linting, and static analysis. This ensures that code adheres to our style guidelines and catches potential errors before they are committed.
   
2. **Consistency Across the Team**: By enforcing coding standards and conventions, pre-commit hooks help maintain a consistent codebase, regardless of individual developers' preferences.
   
3. **Early Detection of Issues**: Pre-commit hooks can run tests and other checks before code is committed, helping to identify issues early in the development process.
   
4. **Increased Productivity**: Automated checks reduce the need for manual code reviews focused on style and formatting, allowing reviewers to concentrate on the logic and functionality of the code.

## Proposed Implementation

   - `black` ` for code formatting
   - `flake8` for linting
   - `pytest` for running tests

**Comment by RebelOfDeath** [comment]
@Ar4l

**Comment by Ar4l** [comment]
As long as it auto-formats to `black` it's okay with me; but we can also leave this for later in the project. This is what I meant with #13.

**Comment by RebelOfDeath** [comment]
added an initial version for the pre-commit configuration file in 63841c13e99ec03c75032ca4df9ca1a5ac49e6ab

**Comment by RebelOfDeath** [comment]
tested that the pre-commit configuration is working in 646a3c57084eede0472e90fbe20d6bfa571ab39a.
