### ISSUE TITLE
WebSocket Endpoint

### ISSUE THREAD

**Issue by RebelOfDeath** [AISE-TUDelft/coco#16]
Introduction of a WebSocket-based serving strategy which would reduce the overall overhead for the requests being made. I think given that we will soon be shifting focus to developing the actual plugins for CoCo it would be nice to have something like this which would (at least in my opinion) be a major improvement WRT prior versions.

**Comment by RebelOfDeath** [comment]
Initial implementation was provided in a7399bfa240fc32c007260f81db7c7140a739491

**Comment by Ar4l** [comment]
Okay I get to implement async streaming in the modified `vllm` file then :)

**Comment by RebelOfDeath** [comment]
@Ar4l, the current implementation has not been validated yet (but it will be with the completion of #18) so I would wait a bit before you actually start adding code to that part of the application, just cuz there is a very high likelihood that it will have to be changed/refactored.

**Comment by RebelOfDeath** [comment]
But it would be pretty cool to be able to stream the completions to the user, we could even do some sort of A/B test to see the impact streaming has on the user's likelihood to accept completions 🤔

**Comment by RebelOfDeath** [comment]
tested implementaion in 5a9c7163ec80048cc381f88f155fd2055acc4026 and ensured that they are working as intended.
