### ISSUE TITLE
Proivde an interface to generate upon given request

### ISSUE THREAD

**Issue by RebelOfDeath** [AISE-TUDelft/coco#6]
Provide an interface to the application layer to be able to invoke a method of sort that generates a completion for a given request and returns it in the intended format to the application.

**Comment by Ar4l** [comment]
As I am extending `LangChain`'s `BaseLLM` with better `vllm` integration, you may use the `BaseLLM` methods (`invoke`/`ainvoke` in this case). I will soon add the respective input/output parsers to ensure the format follows model specifications.

**Comment by Ar4l** [comment]
Done. We generate completions using a LangChain `Runnable`, so this is the interface if you must use one. In practice, this corresponds to the `chain` defined in `server.completions.__init__`.
